/* auto-generated by NAPI-RS */
/* eslint-disable */
/** In-memory agent memory DB with HNSW vector search. */
export declare class AgentMemDb {
  constructor(dim: number)
  /** Create with exact (brute-force) search. O(n) per query. */
  static exact(dim: number): AgentMemDb
  /** Create with custom max_elements for scale. */
  static withMaxElements(dim: number, maxElements: number): AgentMemDb
  /** Store an episode. */
  storeEpisode(episode: Episode): void
  /** Query for similar episodes. embedding: number[], min_reward, top_k. Optional opts for filters. */
  querySimilar(embedding: Array<number>, minReward: number, topK: number, opts?: QueryOptionsJs | undefined | null): Array<Episode>
  /** Save to JSON file. */
  saveToFile(path: string): void
  /** Load from JSON file. */
  static loadFromFile(path: string): AgentMemDb
  /** Prune episodes with timestamp older than cutoff (Unix ms). Episodes without timestamp are kept. */
  pruneOlderThan(timestampCutoffMs: number): number
  /** Prune to keep only the n most recent episodes (by timestamp). */
  pruneKeepNewest(n: number): number
  /** Prune to keep only the n episodes with highest reward. */
  pruneKeepHighestReward(n: number): number
}
export type AgentMemDB = AgentMemDb

/** Disk-backed agent memory DB. Episodes stored in append-only log; index in RAM. */
export declare class AgentMemDbDisk {
  /** Open or create a disk-backed DB at the given directory. Uses HNSW by default. */
  static open(path: string, dim: number): AgentMemDbDisk
  /** Open with exact index and checkpoint enabled for fast restart. Call checkpoint() after stores. */
  static openExactWithCheckpoint(path: string, dim: number): AgentMemDbDisk
  /** Store an episode. */
  storeEpisode(episode: Episode): void
  /** Query for similar episodes. */
  querySimilar(embedding: Array<number>, minReward: number, topK: number, opts?: QueryOptionsJs | undefined | null): Array<Episode>
  /** Persist checkpoint for fast restart (ExactIndex only). No-op for HNSW. */
  checkpoint(): void
  /** Prune episodes with timestamp older than cutoff (Unix ms). */
  pruneOlderThan(timestampCutoffMs: number): number
  /** Prune to keep only the n most recent episodes. */
  pruneKeepNewest(n: number): number
  /** Prune to keep only the n episodes with highest reward. */
  pruneKeepHighestReward(n: number): number
}
export type AgentMemDBDisk = AgentMemDbDisk

/** Create a new Episode. id is auto-generated. */
export declare function createEpisode(taskId: string, stateEmbedding: Array<number>, reward: number, metadata?: any | undefined | null, timestamp?: number | undefined | null, tags?: Array<string> | undefined | null, source?: string | undefined | null, userId?: string | undefined | null): Episode

/** Episode for agent memory. Pass to storeEpisode. */
export interface Episode {
  id: string
  taskId: string
  stateEmbedding: Array<number>
  reward: number
  metadata?: any
  timestamp?: number
  tags?: Array<string>
  source?: string
  userId?: string
}

/** Query options for similarity search. */
export interface QueryOptionsJs {
  minReward: number
  topK: number
  tagsAny?: Array<string>
  tagsAll?: Array<string>
  taskIdPrefix?: string
  timeAfter?: number
  timeBefore?: number
  source?: string
  userId?: string
}
